# -*- coding: utf-8 -*-
"""Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tfweQUTRydegKMiJ72dHKRQ2mzajiJ0r
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import streamlit as st
import plotly.express as px

df_fe = pd.read_csv("https://raw.githubusercontent.com/Prabhav9252/Python-Visualization-Project/refs/heads/main/df_fe.csv")

df_fe.drop(columns="Unnamed: 0",inplace=True)

df_fe

avg_increment = df_fe['increment_percentage'].mean()
avg_salary = df_fe['salary'].mean()
retention_rate = df_fe['termination_flag'].value_counts(normalize=True)['No']*100

# Streamlit Dashboard Title
st.title("Employee KPI Dashboard")

# Display KPI
col1, col2, col3 = st.columns(3)
col1.metric("Average Salary", f"{avg_salary: ,.0f}")
col2.metric("Average Increment", f"{avg_increment:.1f}")
col3.metric("Retention Rate", f"{retention_rate:.1f}%")


# Filters
st.sidebar.header("Filters")
exp_range = st.sidebar.slider("Experience Years" ,
                              min_value = 0,
                              max_value = int(df_fe['experience_years'].max()) +1 ,
                              value = (0, int(df_fe['experience_years'].max())))
termination_filter = st.sidebar.selectbox('Termination Status' , ['All','Active','Terminated'])


#Apply filter
filter_map = {'Active' :'No',
              'Terminated' : 'Yes',
              'All' : 'All'}

flag_value = filter_map[termination_filter]
mask = df_fe['experience_years'].between(exp_range[0],
                                      exp_range[1]) & np.where(flag_value == 'All' ,True, df_fe['termination_flag'] == flag_value)

filtered_df = df_fe[mask]

# ScatterPlot

fig_1 = px.scatter(filtered_df, x='experience_years',
              y='salary',
              color='promotion_hr_based',
              title='Salary Vs Experience By Promotion Status',
              labels = {'experience_years':'Experience (in Years)',
                       'salary':'Salary',
                       'promotion_hr_based':'Promotion Status'},
              color_discrete_map = {'Promotion Pipeline' : '#1f77b4', 'Not In Promotion Pipeline' : '#66d620' }
              )

st.plotly_chart(fig_1,width='stretch')













